language: node_js
  - "8"

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle

install:
  - npm install

script:
  - ganache-cli &
  - sleep 5
  - truffle migrate --network integration
  - truffle test --network integration
