language: node_js
  - "8"

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle@4.1.14

install:
  - npm install

script:
  - ganache-cli &
  - sleep 5
  - truffle test
  - truffle migrate
